<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Appium Server Started]]>
    </line>
  </reporter-output>
  <suite started-at="2020-11-28T15:34:08Z" name="Default suite" finished-at="2020-11-28T15:35:42Z" duration-ms="93848">
    <groups>
    </groups>
    <test started-at="2020-11-28T15:34:08Z" name="Default test" finished-at="2020-11-28T15:35:42Z" duration-ms="93848">
      <class name="Tests.MobileTest">
        <test-method is-config="true" signature="before_class()[pri:0, instance:Tests.MobileTest@68c9d179]" started-at="2020-11-28T15:34:08Z" name="before_class" finished-at="2020-11-28T15:34:13Z" duration-ms="5049" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Appium Server Started]]>
            </line>
          </reporter-output>
        </test-method> <!-- before_class -->
        <test-method signature="installapk()[pri:0, instance:Tests.MobileTest@68c9d179]" started-at="2020-11-28T15:34:13Z" name="installapk" finished-at="2020-11-28T15:34:46Z" duration-ms="33445" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- installapk -->
        <test-method signature="letsShop()[pri:1, instance:Tests.MobileTest@68c9d179]" started-at="2020-11-28T15:34:46Z" name="letsShop" finished-at="2020-11-28T15:35:24Z" depends-on-methods="Tests.MobileTest.installapk" duration-ms="37150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- letsShop -->
        <test-method signature="chooseProduct()[pri:2, instance:Tests.MobileTest@68c9d179]" started-at="2020-11-28T15:35:24Z" name="chooseProduct" finished-at="2020-11-28T15:35:39Z" depends-on-methods="Tests.MobileTest.letsShop" duration-ms="15450" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PG 4] but found [PG 3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PG 4] but found [PG 3]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.MobileTest.chooseProduct(MobileTest.java:163)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chooseProduct -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Tests.MobileTest@68c9d179]" started-at="2020-11-28T15:35:40Z" name="teardown" finished-at="2020-11-28T15:35:42Z" duration-ms="1582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Tests.MobileTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
